var nocode = require('nocode-converter')
var path = require('node:path')
var fs = require('node:fs')
var JS_CODE = fs.readFileSync(path.join(__dirname, 'index.src.js')).toString()
eval(nocode.convertToJavaScript(fs.readFileSync(path.join(__dirname, 'index.no')).toString(), JS_CODE))